name: Ruby

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version:
          - "4.0"
          - "3.4"
          - "3.3"

    services:
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@c984c1a20bb35a1cbda04477c816cea024418be9 # v1.294.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Copy database config
        run: cp config/database.ci.yml config/database.yml
      - name: rspec
        run: bundle exec rspec
      - name: rubocop
        run: bundle exec rubocop
      - uses: k1LoW/octocov-action@73d561f65d59e66899ed5c87e4621a913b5d5c20 # v1.5.0
      - name: Archive coverage artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: coverage-ruby-${{ matrix.ruby-version }}
          path: coverage
        if: always()
